require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/centre_interets", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CentreInteret. As you add validations to CentreInteret, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CentreInteretsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      CentreInteret.create! valid_attributes
      get centre_interets_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      centre_interet = CentreInteret.create! valid_attributes
      get centre_interet_url(centre_interet), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CentreInteret" do
        expect {
          post centre_interets_url,
               params: { centre_interet: valid_attributes }, headers: valid_headers, as: :json
        }.to change(CentreInteret, :count).by(1)
      end

      it "renders a JSON response with the new centre_interet" do
        post centre_interets_url,
             params: { centre_interet: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CentreInteret" do
        expect {
          post centre_interets_url,
               params: { centre_interet: invalid_attributes }, as: :json
        }.to change(CentreInteret, :count).by(0)
      end

      it "renders a JSON response with errors for the new centre_interet" do
        post centre_interets_url,
             params: { centre_interet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested centre_interet" do
        centre_interet = CentreInteret.create! valid_attributes
        patch centre_interet_url(centre_interet),
              params: { centre_interet: new_attributes }, headers: valid_headers, as: :json
        centre_interet.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the centre_interet" do
        centre_interet = CentreInteret.create! valid_attributes
        patch centre_interet_url(centre_interet),
              params: { centre_interet: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the centre_interet" do
        centre_interet = CentreInteret.create! valid_attributes
        patch centre_interet_url(centre_interet),
              params: { centre_interet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested centre_interet" do
      centre_interet = CentreInteret.create! valid_attributes
      expect {
        delete centre_interet_url(centre_interet), headers: valid_headers, as: :json
      }.to change(CentreInteret, :count).by(-1)
    end
  end
end
