require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/habilites_extra_pros", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # HabilitesExtraPro. As you add validations to HabilitesExtraPro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # HabilitesExtraProsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      HabilitesExtraPro.create! valid_attributes
      get habilites_extra_pros_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      habilites_extra_pro = HabilitesExtraPro.create! valid_attributes
      get habilites_extra_pro_url(habilites_extra_pro), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HabilitesExtraPro" do
        expect {
          post habilites_extra_pros_url,
               params: { habilites_extra_pro: valid_attributes }, headers: valid_headers, as: :json
        }.to change(HabilitesExtraPro, :count).by(1)
      end

      it "renders a JSON response with the new habilites_extra_pro" do
        post habilites_extra_pros_url,
             params: { habilites_extra_pro: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HabilitesExtraPro" do
        expect {
          post habilites_extra_pros_url,
               params: { habilites_extra_pro: invalid_attributes }, as: :json
        }.to change(HabilitesExtraPro, :count).by(0)
      end

      it "renders a JSON response with errors for the new habilites_extra_pro" do
        post habilites_extra_pros_url,
             params: { habilites_extra_pro: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested habilites_extra_pro" do
        habilites_extra_pro = HabilitesExtraPro.create! valid_attributes
        patch habilites_extra_pro_url(habilites_extra_pro),
              params: { habilites_extra_pro: new_attributes }, headers: valid_headers, as: :json
        habilites_extra_pro.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the habilites_extra_pro" do
        habilites_extra_pro = HabilitesExtraPro.create! valid_attributes
        patch habilites_extra_pro_url(habilites_extra_pro),
              params: { habilites_extra_pro: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the habilites_extra_pro" do
        habilites_extra_pro = HabilitesExtraPro.create! valid_attributes
        patch habilites_extra_pro_url(habilites_extra_pro),
              params: { habilites_extra_pro: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested habilites_extra_pro" do
      habilites_extra_pro = HabilitesExtraPro.create! valid_attributes
      expect {
        delete habilites_extra_pro_url(habilites_extra_pro), headers: valid_headers, as: :json
      }.to change(HabilitesExtraPro, :count).by(-1)
    end
  end
end
