require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/telephones", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Telephone. As you add validations to Telephone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:telephone).attributes
  }

  let(:invalid_attributes) {
    {
      numero: nil
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # TelephonesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    { "Content-Type": "application/json; charset=utf-8" }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Telephone.create! valid_attributes
      get telephones_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      telephone = Telephone.create! valid_attributes
      get telephone_url(telephone), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Telephone" do
        expect {
          post telephones_url,
               params: { telephone: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Telephone, :count).by(1)
      end

      it "renders a JSON response with the new telephone" do
        post telephones_url,
             params: { telephone: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json; charset=utf-8"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Telephone" do
        expect {
          post telephones_url,
               params: { telephone: invalid_attributes }, as: :json
        }.to change(Telephone, :count).by(0)
      end

      it "renders a JSON response with errors for the new telephone" do
        post telephones_url,
             params: { telephone: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        build(:telephone).attributes
      }

      it "updates the requested telephone" do
        telephone = Telephone.create! valid_attributes
        patch telephone_url(telephone),
              params: { telephone: new_attributes }, headers: valid_headers, as: :json
        telephone.reload
        expect(response).to have_http_status(:ok)
      end

      it "renders a JSON response with the telephone" do
        telephone = Telephone.create! valid_attributes
        patch telephone_url(telephone),
              params: { telephone: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json; charset=utf-8"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the telephone" do
        telephone = Telephone.create! valid_attributes
        patch telephone_url(telephone),
              params: { telephone: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested telephone" do
      telephone = Telephone.create! valid_attributes
      expect {
        delete telephone_url(telephone), headers: valid_headers, as: :json
      }.to change(Telephone, :count).by(-1)
    end
  end
end
